# Generated by Django 6.0.6 on 2026-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("data", models.JSONField()),
                ("created_by", models.IntegerField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
