# Generated by Django 6.0.6 on 2026-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("quantity", models.IntegerField(default=0)),
                ("warehouse_location", models.CharField(max_length=200)),
                ("reorder_level", models.IntegerField(default=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
